// docs/design-system/components/clear-effect/ClearEffect.jsx
import React from "react";
import { Button } from "../button/Button.jsx";

/**
 * Mission-complete celebration — emerald glow stage with a Jost stamp, a mono
 * subline (e.g. the commit that closed the case) and a next-mission CTA.
 */
export function ClearEffect({
  stamp = "Mission Complete!",
  sub,
  ctaLabel = "次のミッションへ →",
  onNext,
  height = 320,
}) {
  return (
    <div
      style={{
        position: "relative",
        height,
        borderRadius: "var(--radius-lg)",
        overflow: "hidden",
        border: "1px solid var(--border-subtle)",
        background: "radial-gradient(120% 100% at 50% 40%, rgba(16,185,129,.18), var(--gray-950) 70%)",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        gap: "var(--space-5)",
        textAlign: "center",
        fontFamily: "var(--font-ui)",
      }}
    >
      <div style={{ fontFamily: "var(--font-hero)", fontWeight: "var(--weight-bold)", textTransform: "uppercase", letterSpacing: "var(--tracking-hero)", fontSize: "var(--text-display)", color: "#6ee7b7", textShadow: "0 0 24px rgba(16,185,129,.6)" }}>
        {stamp}
      </div>
      {sub && <div style={{ color: "#a7f3d0", fontSize: "var(--text-sm)", fontFamily: "var(--font-mono)" }}>{sub}</div>}
      <Button variant="primary" size="lg" onClick={onNext}>{ctaLabel}</Button>
    </div>
  );
}

// noir-client/app/components/ClearEffect.vue
<script setup lang="ts">
// Mission-complete celebration — emerald glow stage with a Jost stamp, a mono
// subline (e.g. the commit that closed the case) and a next-mission CTA.
withDefaults(defineProps<{
  stamp?: string
  sub?: string
  ctaLabel?: string
}>(), {
  stamp: 'Mission Complete!',
  sub: '$ git push — case closed. snapshot saved.',
  ctaLabel: '次のミッションへ →',
})
defineEmits<{ (e: 'next'): void }>()
</script>

<template>
  <div class="stage">
    <div class="stamp">{{ stamp }}</div>
    <div v-if="sub" class="sub">{{ sub }}</div>
    <NoirButton variant="primary" size="lg" @click="$emit('next')">{{ ctaLabel }}</NoirButton>
  </div>
</template>

<style scoped>
.stage {
  position: relative;
  height: 100%;
  min-height: 280px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: var(--space-5);
  text-align: center;
  background: radial-gradient(120% 100% at 50% 40%, rgba(16, 185, 129, 0.18), var(--gray-950) 70%);
}
.stamp {
  font-family: var(--font-hero);
  font-weight: var(--weight-bold);
  text-transform: uppercase;
  letter-spacing: var(--tracking-hero);
  font-size: var(--text-display);
  color: #6ee7b7;
  text-shadow: 0 0 24px rgba(16, 185, 129, 0.6);
}
.sub {
  color: #a7f3d0;
  font-size: var(--text-sm);
  font-family: var(--font-mono);
}
</style>
